# -*- encoding: utf-8 -*-

=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "polar-rb/version"

Gem::Specification.new do |s|
  s.name        = "polar-rb"
  s.version     = PolarRb::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["b2bhelpdesk@polar.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Polar Accesslink API Ruby Gem"
  s.description = "Polar Accesslink API documentation"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'httpx', '~> 1.0', '>= 1.0.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
