=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PolarRb::CardioLoadStatusEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarRb::CardioLoadStatusEnum do
  let(:instance) { PolarRb::CardioLoadStatusEnum.new }

  describe 'test an instance of CardioLoadStatusEnum' do
    it 'should create an instance of CardioLoadStatusEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PolarRb::CardioLoadStatusEnum)
    end
  end

end
