=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PolarRb::Nights
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarRb::Nights do
  let(:instance) { PolarRb::Nights.new }

  describe 'test an instance of Nights' do
    it 'should create an instance of Nights' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PolarRb::Nights)
    end
  end

  describe 'test attribute "nights"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
