=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PolarRb::TrainingLoadProSample
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarRb::TrainingLoadProSample do
  let(:instance) { PolarRb::TrainingLoadProSample.new }

  describe 'test an instance of TrainingLoadProSample' do
    it 'should create an instance of TrainingLoadProSample' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PolarRb::TrainingLoadProSample)
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cardio_load"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "muscle_load"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "perceived_load"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cardio_load_interpretation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "muscle_load_interpretation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "perceived_load_interpretation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user_rpe"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
