=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

# Common files
require 'polar-rb/api_client'
require 'polar-rb/api_error'
require 'polar-rb/version'
require 'polar-rb/configuration'

# Models
require 'polar-rb/models/activity'
require 'polar-rb/models/activity_log'
require 'polar-rb/models/activity_step_sample'
require 'polar-rb/models/activity_step_samples'
require 'polar-rb/models/activity_zone_sample'
require 'polar-rb/models/activity_zone_samples'
require 'polar-rb/models/alertness'
require 'polar-rb/models/alertness_hourly_data'
require 'polar-rb/models/available_sleep'
require 'polar-rb/models/available_sleeps'
require 'polar-rb/models/available_user_data'
require 'polar-rb/models/available_user_datas'
require 'polar-rb/models/cardio_load'
require 'polar-rb/models/cardio_load_levels'
require 'polar-rb/models/cardio_load_status_enum'
require 'polar-rb/models/circadian_bedtime'
require 'polar-rb/models/continuous_heartrate'
require 'polar-rb/models/continuous_heartrate_heart_rate_samples'
require 'polar-rb/models/created_webhook'
require 'polar-rb/models/created_webhook_data'
require 'polar-rb/models/duration_zone'
require 'polar-rb/models/error'
require 'polar-rb/models/exercise'
require 'polar-rb/models/exercise_hash_id'
require 'polar-rb/models/exercises'
require 'polar-rb/models/heart_rate'
require 'polar-rb/models/nightly_recharge'
require 'polar-rb/models/nights'
require 'polar-rb/models/physical_information'
require 'polar-rb/models/physical_informations'
require 'polar-rb/models/recharges'
require 'polar-rb/models/register'
require 'polar-rb/models/sample'
require 'polar-rb/models/samples'
require 'polar-rb/models/sleep'
require 'polar-rb/models/training_load_pro_load_enum'
require 'polar-rb/models/training_load_pro_rpe_enum'
require 'polar-rb/models/training_load_pro_sample'
require 'polar-rb/models/transaction_location'
require 'polar-rb/models/user'
require 'polar-rb/models/user_extra_info'
require 'polar-rb/models/webhook_info'
require 'polar-rb/models/webhook_info_data'
require 'polar-rb/models/webhook_patch'
require 'polar-rb/models/webhook_payload_alertness'
require 'polar-rb/models/webhook_payload_circadian_bedtime'
require 'polar-rb/models/webhook_payload_continuous_heart_rate'
require 'polar-rb/models/webhook_payload_exercise'
require 'polar-rb/models/webhook_payload_sleep'
require 'polar-rb/models/webhook_ping'
require 'polar-rb/models/webhook_request'
require 'polar-rb/models/webhook_type'
require 'polar-rb/models/zone'
require 'polar-rb/models/zones'

# APIs
require 'polar-rb/api/cardio_load_beta_api'
require 'polar-rb/api/continuous_heart_rate_beta_api'
require 'polar-rb/api/daily_activity_api'
require 'polar-rb/api/exercises_api'
require 'polar-rb/api/nightly_recharge_api'
require 'polar-rb/api/physical_info_api'
require 'polar-rb/api/pull_notifications_api'
require 'polar-rb/api/sleep_api'
require 'polar-rb/api/sleep_wisetrade_beta_api'
require 'polar-rb/api/training_data_api'
require 'polar-rb/api/users_api'
require 'polar-rb/api/webhooks_api'

module PolarRb
  class << self
    # Customize default settings for the SDK using block.
    #   PolarRb.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
